### ISSUE TITLE
Search function not working correctly.

### ISSUE THREAD

**Issue by bsknblc** [aylinaydincs/CS320#7]
From repository, we are having a failure. 
`PathVariableMethodArgumentResolver.handleMissingValue(PathVariableMethodArgumentResolver.java:101)` 

@eyubsah 
@bsknblc 
@yigitcicioglu 
@EkinDevrimSahinkaya 
@aylinaydincs

**Comment by aylinaydincs** [comment]
It is working corectly, fill the requestbody for search through the movie.
